### ISSUE TITLE
Python error 

### ISSUE THREAD

**Issue by amruta-meh** [gustavowillam/SmartMapPlugin#21]
Hello,
I received this python error after installing the plugin:

AttributeError: type object 'object' has no attribute 'dtype' 
Traceback (most recent call last):
  File "C:/Users/ASUS/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 653, in run
    self.df_limite = pd.DataFrame(columns = ['Coord_X' , 'Coord_Y'])
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\pandas\core\frame.py", line 435, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\pandas\core\internals\construction.py", line 239, in init_dict
    val = construct_1d_arraylike_from_scalar(np.nan, len(index), nan_dtype)
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\pandas\core\dtypes\cast.py", line 1449, in construct_1d_arraylike_from_scalar
    dtype = dtype.dtype
AttributeError: type object 'object' has no attribute 'dtype'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.16.6-Hannover Hannover, bfd36fddc9 

Please help. Thanks :) 
A

**Comment by gustavowillam** [comment]
Hi, @amruta-meh 

Are you using the latest version of smart Map? Version 1.1.1 ?
If not, I suggest updating to the latest version found in the QGIS repository.
I suggest you also update QGIS to the latest stable version. 3.22 LTR.

Thanks,

**Comment by amruta-meh** [comment]
Hello @gustavowillam. I updated to the latest version of QGIS and the plugin worked! Sorry for bothering. Thanks :)
