### ISSUE TITLE
Erro ao interpolar

### ISSUE THREAD

**Issue by saranishida** [gustavowillam/SmartMapPlugin#25]
2022-06-02T16:22:36     WARNING    Traceback (most recent call last):
              File "C:\Users/Sara/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 3567, in pushButton_Krigagem_clicked
              z_est_py, ss = OK.execute(xygrid, n_closest_points=n_neig, radius=raio_busca)
              File "C:\Users/Sara/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\krig\kriging.py", line 305, in execute
              zvalues, sigmasq = self._exec_loop(a, xypoints,n)
              File "C:\Users/Sara/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\krig\kriging.py", line 260, in _exec_loop
              x = scipy.linalg.solve(a, b)
              File "C:\PROGRA~1\QGIS31~1.11\apps\Python39\lib\site-packages\scipy\linalg\basic.py", line 214, in solve
              _solve_check(n, info)
              File "C:\PROGRA~1\QGIS31~1.11\apps\Python39\lib\site-packages\scipy\linalg\basic.py", line 29, in _solve_check
              raise LinAlgError('Matrix is singular.')
             numpy.linalg.LinAlgError: Matrix is singular.

**Comment by gustavowillam** [comment]
Hi, @saranishida!

Update to the latest LTR version of QGIS (3.22.7) https://qgis.org/downloads/QGIS-OSGeo4W-3.22.7-1.msi 
And then install the latest version of Smart Map from the QGIS repository.
