### ISSUE TITLE
Error when opening the plugin

### ISSUE THREAD

**Issue by chrisgraf** [gustavowillam/SmartMapPlugin#29]
An error has occurred while executing Python code: 

```
TypeError: setValue(self, int): argument 1 has unexpected type 'float' 
Traceback (most recent call last):
  File "/home/graf/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/Smart_Map.py", line 656, in run
    self.reset_gui()
  File "/home/graf/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/Smart_Map.py", line 735, in reset_gui
    self.dlg.horizontalSlider_Range.setValue(0.001)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
```

Python version: 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] 
QGIS version: 3.22.4-Białowieża Białowieża, exported

**Comment by gustavowillam** [comment]
This error was fixed in version 1.3 of the plugin already available in the qgis plugin repository.
Install the new version to fix the issue.
