### ISSUE TITLE
Um erro ocorreu enquanto executava o código Python: 

### ISSUE THREAD

**Issue by Nakakojinelson** [gustavowillam/SmartMapPlugin#37]
Olá caro senhores desenvolvedores, estou tentante rodar o smatmap no linux mint 21.1 xfce, instalei o qgis białowieża, pois no windows rodava bem juntamente com o smatmap. Como será que podemos resolver isso?  

TypeError: setValue(self, int): argument 1 has unexpected type 'float' 
Traceback (most recent call last):
  File "/home/naru/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/Smart_Map.py", line 656, in run
    self.reset_gui()
  File "/home/naru/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/Smart_Map.py", line 735, in reset_gui
    self.dlg.horizontalSlider_Range.setValue(0.001)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'

**Comment by gusluz** [comment]
Olá, aparentemente um erro semelhante está ocorrendo comigo:

Um erro ocorreu enquanto executava o código Python: 

TypeError: setValue(self, int): argument 1 has unexpected type 'float' 
Traceback (most recent call last):
  File "/home/gustavoluz/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/Smart_Map.py", line 985, in mMapLayerComboBox_changed
    self.reset_gui()
  File "/home/gustavoluz/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/Smart_Map.py", line 735, in reset_gui
    self.dlg.horizontalSlider_Range.setValue(0.001)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'


Versão do Python: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] 
Versão do QGIS: 3.22.16-Białowieża Białowieża, exported

**Comment by gustavowillam** [comment]
Este erro foi corrigido na versão 1.3 do plugin já disponivel no repositório de plugins do qgis. 
Instale a nova versão para corrigir o problema e atualize o Qgis para a versão 3.28 LTR.
