### ISSUE TITLE
TypeError: Unexpected keyword argument {'n_jobs': -1}

### ISSUE THREAD

**Issue by gvanhavre** [gustavowillam/SmartMapPlugin#38]
Olá,

Fiz um primeiro teste com seu plugin no QGIS 3.26.1 em Linux Mint 20.3, com dados do projeto Dryad (Paleoclima) que tem rasters de 55km. Instalei todas as dependências do python. Ao clicar em Interpolate, sem mexer nas opções, deu o seguinte erro:

2023-03-24T08:08:56     WARNING    Traceback (most recent call last):
              File "/home***/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/Smart_Map.py", line 3702, in pushButton_Krigagem_clicked
              z_est_py, ss = OK.execute(xygrid, n_closest_points=n_neig, radius=raio_busca)
              File "/home/***/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/krig/kriging.py", line 305, in execute
              zvalues, sigmasq = self._exec_loop(a, xypoints,n)
              File "/home/***/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/krig/kriging.py", line 204, in _exec_loop
              dist_all,ids_all=tree.query(xypts,k=self.n_closest_points,p=2,
              File "_ckdtree.pyx", line 783, in scipy.spatial._ckdtree.cKDTree.query
              File "_ckdtree.pyx", line 387, in scipy.spatial._ckdtree.get_num_workers
             TypeError: Unexpected keyword argument {'n_jobs': -1}

Faltou instalar algo? Ou estou fazendo errado?

**Comment by gustavowillam** [comment]
Olá, 

A versão QGIS 3.26 não é uma versão LTR, uma sugestão seria instalar a versão QGIS 3.22 ou QGIS 3.28 que seja LTR. 

O erro que está apresentando é em uma biblioteca python (scipy) na função: scipy.spatial._ckdtree.get_num_workers 

Possível problema: A versão do python que está sendo executada no QGIS pode estar apresentando alguma incompatibilibidade com esta biblioteca python. 

Tente trocar a versão do QGIS instalada, instale a versão mais recente. QGIS 3.28 LTR. 

Já tentou execultar o seu projeto em uma máquina com Sistema Operacional Windows ? 
Seria bom tentar para ver se o problema persiste. 

Abraços!

**Comment by gustavowillam** [comment]
Este erro foi corrigido na versão 1.3 do plugin já disponivel no repositório de plugins do qgis. 
Instale a nova versão para corrigir o problema e atualize o Qgis para a versão 3.28 LTR.
