### ISSUE TITLE
Erro Código Phyton

### ISSUE THREAD

**Issue by eltonrosa01** [gustavowillam/SmartMapPlugin#46]
Está ocorrendo esse erro como proceder?

Um erro ocorreu enquanto executava o código Python: 

KeyError: 'H2O(pH)' 
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\site-packages\pandas\core\indexes\base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'H2O(pH)'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users/ategm/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 1670, in pushButton_ImportQGIS_clicked
    self.list_index_outlier = functions.localizar_outlier(self.df, self.v_target)
  File "C:\Users/ategm/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\utils\functions.py", line 475, in localizar_outlier
    z_mean = df[colname].mean()  #media
  File "C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\site-packages\pandas\core\frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\site-packages\pandas\core\indexes\base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'H2O(pH)'

**Comment by gustavowillam** [comment]
Olá Elton. 

Renomei sua coluna para H2O_pH, removendo o parenteses, no QGIS, antes de execultar o plugin.
