### ISSUE TITLE
Interpolation fail error

### ISSUE THREAD

**Issue by mbayad33** [gustavowillam/SmartMapPlugin#47]
Hello ,

I have tried to ordinary kriging using SmartmapPluging but each time I get this error when I click interpolate: 

This error is generated when I select non-linear model (e.g. polynomial). But the plugin works fine with linear model for me.

Could you please help solve this error?

An error has occurred while executing Python code: 

numpy.linalg.LinAlgError: Matrix is singular. 
Traceback (most recent call last):
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 3705, in pushButton_Krigagem_clicked
    z_est_py, ss = OK.execute(xygrid, n_closest_points=n_neig, radius=raio_busca)
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\krig\kriging.py", line 328, in execute
    zvalues, sigmasq = self._exec_loop(a, xypoints,n)
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\krig\kriging.py", line 282, in _exec_loop
    x = scipy.linalg.solve(a, b)
  File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\scipy\linalg\basic.py", line 214, in solve
    _solve_check(n, info)
  File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\scipy\linalg\basic.py", line 29, in _solve_check
    raise LinAlgError('Matrix is singular.')
numpy.linalg.LinAlgError: Matrix is singular.

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.1-Firenze Firenze, fde3b8fbb8c

**Comment by gustavowillam** [comment]
Which plugin version are you using?
Install the latest version (1.3.2): https://plugins.qgis.org/plugins/Smart_Map/version/1.3.2/
And check again if the error persists.
