### ISSUE TITLE
Erro ao chamar o método Class Factory().  MacOS Catalina Versão 10.15.7

### ISSUE THREAD

**Issue by MarcusAlmansaUFSM** [gustavowillam/SmartMapPlugin#6]
**Boa noite, sou usuário de MecOS Catalina, e gostaria de obter ajuda para solucionar o seguinte problema que encontrei ao tentar instalar o Smarmap, "Impossível carregar complemento 'Smart_Map' Devido a um erro ao chamar o método Class Factory()." 
Não sei se o problema está relacionando com alguma biblioteca do Python ou coisa do tipo, utilizo o Qgis 3.10.2, porém já tentei com versões mais recentes e o problema continuou.**

ModuleNotFoundError: No module named 'PIL' 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/marcusalmansa/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/__init__.py", line 36, in classFactory
    from .Smart_Map import smart_map
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/marcusalmansa/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/Smart_Map.py", line 66, in 
    from PIL import Image
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'PIL'

Versão do Python: 3.8.5 (v3.8.5:580fbb018f, Jul 20 2020, 12:11:27) [Clang 6.0 (clang-600.0.57)] 
Versão do QGIS: 3.10.11-A Coruña A Coruña, exported 

Caminho do Python:
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/marcusalmansa/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/marcusalmansa/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/F/Python/3.8
/Library/Frameworks/Python.framework/Versions/3.8/lib/python38.zip
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages
/Users/marcusalmansa/Library/Application Support/QGIS/QGIS3/profiles/default/python

**Comment by pedroamarazzo** [comment]
Boa tarde, Marcus
Esse erro costuma ocorrer quando se utiliza o instalador .msi. Tente instalar a versão estável mais recente do Qgis (3.16) via instalador .exe (mais abaixo na página de download) e veja se o erro persiste.

**Comment by gustavowillam** [comment]
Olá Marcus. 
O problema é uma incompatibilidade da biblioteca PIL do Python para o MacOS. 
Eu disponibilizei uma atualização do Smart-Map que pode ser encontrada no repositório do QGIS (https://plugins.qgis.org/plugins/Smart_Map/) ou no GitHub (https://github.com/gustavowillam/SmartMapPlugin/releases/download/v1.1/Smart_Map.zip) para o plugin versão 1.1 para corrigir o problema. 
Eu espero que essa atualização possa resolver o seu problema. 
Estou a disposição. 
Muito Obrigado e desculpe pela demora!

**Comment by gustavowillam** [comment]
Ola @MarcusAlmansaUFSM , a versão 1.1 já está disponível no repositório do QGIS. 
Por gentileza, faça a instalação dessa versão e me informe se seu problema foi resolvido.
Abraços!

**Comment by MarcusAlmansaUFSM** [comment]
**- Boa tarde Gustavo, o erro infelizmente continuou. Mas acredito que o problema também pode estar relacionado ao meu Mac por ser um macbook mais antigo, estou usando um patch para poder rodar o sistema operacional Catalina que é um dos mais atuais e não teria mais suporte para o ano do meu macbook. Já sofri com alguns problemas de incompatibilidade por causa desse patch, como para usar o office. Para solucionar esse problema com office segui os passos desse tuturial https://www.youtube.com/watch?v=NLcRBxmPt8U&ab_channel=Rafael_info.**


Impossível carregar complemento 'Smart_Map' Devido a um erro ao chamar o método Class Factory(). 

ImportError: dlopen(/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/_imaging.cpython-38-darwin.so, 2): Library not loaded: /opt/X11/lib/libxcb.1.dylib   Referenced from: /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/_imaging.cpython-38-darwin.so   Reason: image not found 
Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/marcusalmansa/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/__init__.py", line 36, in classFactory
    from .Smart_Map import smart_map
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/marcusalmansa/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/Smart_Map.py", line 75, in 
    import matplotlib.pyplot as plt1  #plot map of points Limite Area
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/pyplot.py", line 36, in 
    import matplotlib.colorbar
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/colorbar.py", line 44, in 
    import matplotlib.contour as contour
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/contour.py", line 17, in 
    import matplotlib.text as text
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/text.py", line 16, in 
    from .textpath import TextPath  # Unused, but imported by others.
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/textpath.py", line 11, in 
    from matplotlib.mathtext import MathTextParser
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/mathtext.py", line 27, in 
    from PIL import Image
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/Image.py", line 94, in 
    from . import _imaging as core
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: dlopen(/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/_imaging.cpython-38-darwin.so, 2): Library not loaded: /opt/X11/lib/libxcb.1.dylib
  Referenced from: /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/_imaging.cpython-38-darwin.so
  Reason: image not found


Versão do Python: 3.8.7 (default, Feb 10 2021, 09:04:08) [Clang 12.0.0 (clang-1200.0.32.29)] 
Versão do QGIS: 3.16.10-Hannover Hannover, e5b665e952 

Caminho do Python:
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python
/Users/marcusalmansa/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/marcusalmansa/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/pandas-1.1.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/pyproj-2.6.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/snuggs-1.4.7-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Fiona-1.8.13.post1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/rasterio-1.1.5-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/opencv_contrib_python-4.3.0.36-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/numpy-1.20.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/geopandas-0.8.1-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/GDAL-3.2.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/cftime-1.2.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/click_plugins-1.1.1-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/lib-dynload
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/scipy-1.5.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/statsmodels-0.11.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Rtree-0.9.4-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python38.zip
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/netCDF4-1.5.4-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/affine-2.3.0-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/patsy-0.5.1-py3.8.egg
/Users/marcusalmansa/Library/Application Support/QGIS/QGIS3/profiles/default/python

**Comment by gustavowillam** [comment]
Olá Marcus, o problema está ocorrendo devido a uma incompatibilidade da biblioteca Python PIL na versão 3.16 do QGIS. 
Ocorre o seguinte erro: 
ImportError: dlopen(/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/_imaging.cpython-38-darwin.so, 2): Library not loaded: /opt/X11/lib/libxcb.1.dylib Referenced from:

Ou seja está ocorrendo um erro de importação da biblioteca. 

Para solucionar o problema utilize a versão 3.20 do QGIS que corrige esse erro de biblioteca Python.
