### ISSUE TITLE
numpy.linalg.LinAlgError: Matrix is singular. 

### ISSUE THREAD

**Issue by MiKwie** [gustavowillam/SmartMapPlugin#68]
I do not know how to tackle this problem, interpolation doesn't work. Machine learning works btw.
numpy.linalg.LinAlgError: Matrix is singular. 
Traceback (most recent call last):
  File "C:\Users/0031225/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 3705, in pushButton_Krigagem_clicked
    z_est_py, ss = OK.execute(xygrid, n_closest_points=n_neig, radius=raio_busca)
  File "C:\Users/0031225/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\krig\kriging.py", line 329, in execute
    zvalues, sigmasq = self._exec_loop(a, xypoints,n)
  File "C:\Users/0031225/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\krig\kriging.py", line 283, in _exec_loop
    x = scipy.linalg.solve(a, b)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\scipy\linalg\basic.py", line 214, in solve
    _solve_check(n, info)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\scipy\linalg\basic.py", line 29, in _solve_check
    raise LinAlgError('Matrix is singular.')
numpy.linalg.LinAlgError: Matrix is singular.

**Comment by gustavowillam** [comment]
A new version of Smart-Map is available in the QGIS repository. Install the new version (1.4) together with the latest stable version of QGIS (3.34 LTR).
