### ISSUE TITLE
Erro Phyton

### ISSUE THREAD

**Issue by liceliss** [gustavowillam/SmartMapPlugin#71]
Bom dia!

Estou tentando gerar o mapa mas aparece o seguinte erro:

WARNING    Traceback (most recent call last):
              File "C:\Users/AliceSantos/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 3773, in pushButton_Krigagem_clicked
              z_est_py, ss = OK.execute(xygrid, n_closest_points=n_neig, radius=raio_busca)
              File "C:\Users/AliceSantos/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\krig\kriging.py", line 330, in execute
              zvalues, sigmasq = self._exec_loop(a, xypoints,n)
              File "C:\Users/AliceSantos/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\krig\kriging.py", line 284, in _exec_loop
              x = scipy.linalg.solve(a, b)
              File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\scipy\linalg\_basic.py", line 223, in solve
              _solve_check(n, info)
              File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\scipy\linalg\_basic.py", line 29, in _solve_check
              raise LinAlgError('Matrix is singular.')
             numpy.linalg.LinAlgError: Matrix is singular.

Conseguiria me ajudar?

Obrigada!

**Comment by gustavowillam** [comment]
A new version of Smart-Map is available for QGIS versions 3.28 and 3.34. Please install the new version to fix the error described above.
