### ISSUE TITLE
A layer selecionada possui 6764 pontos amostrados. O limite máximo suportado pelo plugin para a layer de entrada é: 5000 pontos.

### ISSUE THREAD

**Issue by FelipeGSF** [gustavowillam/SmartMapPlugin#86]
importei os dados CSV para o QGIS, salvei em coordenadas UTM, limpei os pontos que não fazia sentido estar ali no arquivo, abri o Smart Map e selecionei as 4 CheckBox (ExportarRaster, Exportar ShapeFile de pontos, Exibir Gráficos e Mapas em uma janela Externa e Exportar ShapeFile de Poligonos) então selecionei a minha camada de pontos de rendimento da colheita e selecionei a coluna de dados do rendimento de colheita, então quando pedi para Importar no Smart Map ele deu as msg: "A layer selecionada possui 6764 pontos amostrados.
O limite máximo suportado pelo plugin para a layer de entrada é: 5000 pontos.
Deseja realizar uma reamostragem de pontos?
|SIM|      |NÃO|"

Então escolhi sim, e ele começou os processos e em seguida me deu outra mensagem: "Deseja salvar os pontos reamostrados em uma nova layer Qgis? |SIM|       |NÃO|  "

Então cliquei em sim pela primeira vez e nada acontece e dá o erro mostrado na barra de mensagens do QGIS.
O mesmo acontece clicando em não nessa mesma caixa de dialogo.

Mensagens dadas nas caixas de mensagens de erro do QGIS:
[ADVERTENCIA PYTHON]
2024-09-13T11:20:32     WARNING    warning:C:\Users/felipe.gasques/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py:1558: DeprecationWarning: QgsVectorFileWriter.writeAsVectorFormat() is deprecated
              QgsVectorFileWriter.writeAsVectorFormat(selectedLayer, os.path.join(self.path_absolute , '0_Dados.csv'), "utf-8", lyrCRS, "CSV")
             
             traceback: File "C:\Users/felipe.gasques/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 676, in run
              result = self.dlg.exec_() #button OK
              File "C:\Users/felipe.gasques/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 1558, in pushButton_ImportQGIS_clicked
              QgsVectorFileWriter.writeAsVectorFormat(selectedLayer, os.path.join(self.path_absolute , '0_Dados.csv'), "utf-8", lyrCRS, "CSV")
             
2024-09-13T11:21:54     WARNING    warning:C:\Users/felipe.gasques/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py:8771: DeprecationWarning: QgsCoordinateReferenceSystem constructor is deprecated
              spatRef = QgsCoordinateReferenceSystem(int(crs), QgsCoordinateReferenceSystem.EpsgCrsId)
             
             traceback: File "C:\Users/felipe.gasques/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 676, in run
              result = self.dlg.exec_() #button OK
              File "C:\Users/felipe.gasques/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 1684, in pushButton_ImportQGIS_clicked
              self.export_shapefile_resampled_to_qgis(Input_Table, Output_Layer_File_shp, Output_Layer_Name)
              File "C:\Users/felipe.gasques/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 8771, in export_shapefile_resampled_to_qgis
              spatRef = QgsCoordinateReferenceSystem(int(crs), QgsCoordinateReferenceSystem.EpsgCrsId)
             
2024-09-13T11:21:54     WARNING    warning:C:\Users/felipe.gasques/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py:8784: DeprecationWarning: QgsVectorFileWriter constructor is deprecated
              outLayer = QgsVectorFileWriter(Output_Layer_File_shp, None, fields1, QgsWkbTypes.Point, spatRef)
             
             traceback: File "C:\Users/felipe.gasques/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 676, in run
              result = self.dlg.exec_() #button OK
              File "C:\Users/felipe.gasques/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 1684, in pushButton_ImportQGIS_clicked
              self.export_shapefile_resampled_to_qgis(Input_Table, Output_Layer_File_shp, Output_Layer_Name)
              File "C:\Users/felipe.gasques/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 8784, in export_shapefile_resampled_to_qgis
              outLayer = QgsVectorFileWriter(Output_Layer_File_shp, None, fields1, QgsWkbTypes.Point, spatRef)
             

[ERRO PYTHON]
2024-09-13T11:21:54     WARNING    Traceback (most recent call last):
              File "C:\Users/felipe.gasques/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Smart_Map\Smart_Map.py", line 1750, in pushButton_ImportQGIS_clicked
              self.Num_Points_X = int((float(self.Cord_X_max) - float(self.Cord_X_min)) / float(self.Pixel_Size_X))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             ValueError: cannot convert float NaN to integer
             

[MENSAGEM DE ERRO]
2024-09-13T11:21:54     WARNING    Erro Python : Um erro ocorreu enquanto executava o código Python: Consulte o registro de mensagens (Erro Python) para mais detalhes.

**Comment by FelipeGSF** [comment]
Tem como aumentar a quantidade de Pontos Suportados pelo Plugin para Layer de Entrada?

**Comment by gustavowillam** [comment]
Com relação ao erro: ValueError: cannot convert float NaN to integer, está relacionado a valores nulos (NaN). Antes de importar a layer de pontos, configure a layer de contorno da área na aba GRID para setar os limites do contorno. 
Com relação a suportar mais pontos, estamos trabalhando para otimizar esta funcionalidade. Pretendemos disponibilizar para a próxima versão LTR do QGIS.
