### ISSUE TITLE
issue generating raster- color value issue

### ISSUE THREAD

**Issue by annaguidi** [gustavowillam/SmartMapPlugin#88]
here is my error:

Traceback (most recent call last):
              File "/Users/aguidi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/Smart_Map.py", line 3883, in pushButton_Krigagem_clicked
              Output_Layer_File_tiff = self.export_raster_to_qgis(Input_Table, Output_Layer_File_tiff, Output_Layer_Name, z_field)
              File "/Users/aguidi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/Smart_Map.py", line 8424, in export_raster_to_qgis
              self.define_raster_color_ramp(rlayer, Output_Layer_Name)
              File "/Users/aguidi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/Smart_Map.py", line 8599, in define_raster_color_ramp
              c1 = [ int(element) for element in rp['color1'].split(',') ] #first color Ex: red
              File "/Users/aguidi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Smart_Map/Smart_Map.py", line 8599, in 
              c1 = [ int(element) for element in rp['color1'].split(',') ] #first color Ex: red
             ValueError: invalid literal for int() with base 10: 'rgb:0.84313725490196079'
             
            QGIS version: 3.38.3 grenoble
            Python version: 3.9.5
            Mac version: 15.0 (sequoia)
            
            used latest version of the plugin

**Comment by gustavowillam** [comment]
Your version of QGIS (3.38) is not LTR (Long Term Release). Please use Smart-Map with stable versions of QGIS (3.28 or 3.34).
